export const SET_GROUPS = 'SET_GROUPS';
export const SET_SELECTED_GROUP = 'SET_SELECTED_GROUP';
export const SET_GROUP_DETAILS = 'SET_GROUP_DETAILS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const MARK_TASK_COMPLETED = 'MARK_TASK_COMPLETED';
export const CLEAR_STATE = "CLEAR_STATE";
